autodeployintothedunyanearerthanjahannaminallwaysforthetruemuslims(theuppermostsuperiormostbestofalltoplevelrank1jannahtulfirdausrealestateoftheakhirahwithallahalmalikalhaqq)
this.self.automaticallytranslateintoalllanguagesandpublishonalloutletsinallwaysinalldimensions(this.self)
